import type {ShotSpec} from './shots';

export const SHOT_SPECS: Record<string, ShotSpec> = {
  SC01: {kind: 'title', lecname: "三司与得病日", agenda: ["三才立位", "司天=起点", "十二字诀", "年命安宫", "司地逐宫数", "司人阴退", "口径警示"]},
  SC02: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "说出三司名字"}},
  SC03: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.2895}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.529}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.7685}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.9714}, {k: 'focus', zhi: "寅", rel: 0.96}], centerNote: "知道司天从哪来"}},
  SC04: {kind: 'slide', slide: {kind: 'points', title: "十二字诀", sub: "能背这句", items: ["安错了宫，后面读出来的经和号全跟着偏", "三司的关系，书里给了一句话，司天定局，司地定位，司人定人"]}},
  SC05: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.1771}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.3042}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.4313}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.5584}, {k: 'focus', zhi: "寅", rel: 0.6384}], centerNote: "知道常错在哪"}},
  SC06: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.3382}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.6263}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.9145}, {k: 'focus', zhi: "寅", rel: 0.96}], centerNote: "会自己数出司地"}},
  SC07: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.2521}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.4541}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.6562}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.8583}, {k: 'focus', zhi: "寅", rel: 0.9383}], centerNote: "记住阴退"}},
  SC08: {kind: 'pan', pan: {plate: ['', '亥', '甲', '卯'], sansi: ['卯', '午', '未'], stage: 'sansi', events: [{k: 'mark', zhi: "卯", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "辰", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "巳", text: "2", tone: "ink", rel: 0.0717}, {k: 'mark', zhi: "午", text: "3", tone: "cinnabar", rel: 0.0934}, {k: 'mark', zhi: "午", text: "司地", tone: "cinnabar", rel: 0.1151}, {k: 'mark', zhi: "未", text: "司人", tone: "cinnabar", rel: 0.5718}, {k: 'focus', zhi: "卯", rel: 0.6518}], centerNote: "会排第二个例子"}},
  SC09: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.2701}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.4901}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.7102}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.9302}, {k: 'focus', zhi: "寅", rel: 0.96}], centerNote: "分清得病日与病经"}},
  SC10: {kind: 'slide', slide: {kind: 'points', title: "支与干分工", sub: "说出两条路的起点", items: ["地支立位，天干取证，两件事各走各的路", "有人排到这一步会想，两件事能不能合成一件", "合不得，一条走支，一条走干，起点都不一样"]}},
  SC11: {kind: 'slide', slide: {kind: 'points', title: "位与气", sub: "明白一天两用", items: ["书里给这两件事起了个名，一个叫位，一个叫气", "同一个日子，在盘里要当两样东西用", "一是位，地支立司天，定下整局的坐标", "一是气，天干铺进天盘，在司天宫上落成一个证位", "举个例子，甲寅日得病", "地支这一路，寅立司天，司天寅，数三宫到司地巳，退一到司人辰"]}},
  SC12: {kind: 'slide', slide: {kind: 'points', title: "六层并列", sub: "知道六层不是相加", items: ["第三层，是传变，看六天怎么传经，这一层在第十二讲展开", "第六层，是运气，看五运六气怎么加临，在丁部", "看盘最忌讳的，是把六七个指标混成一锅粥", "盘不只一层，书里另列了六样东西", "不会，各层回答的问题不一样，谁也不压谁"]}},
  SC13: {kind: 'slide', slide: {kind: 'points', title: "口径警示", sub: "记住换算要标出处", items: ["号是死的，歌也，是死的，查出来是什么就是什么", "古书说一个时字，有时，指时辰，有时指日子", "有时又，指病程里的第几日", "再凭印象说一句大凶，或者一句无碍", "凡是说到时间，都得先把口径讲清楚"]}},
  SC14: {kind: 'table', cols: [{t: '地支'}, {t: '六经'}, {t: '地支'}, {t: '六经'}], rows: [["辰", "太阳", "戌", "太阳"], ["卯", "阳明", "酉", "阳明"], ["寅", "少阳", "申", "少阳"], ["丑", "太阴", "未", "太阴"], ["子", "少阴", "午", "少阴"], ["巳", "厥阴", "亥", "厥阴"]], rowH: 46, perCell: 5, x: 400, y: 232, w: 480, title: "地支归六经", caption: "三支一经，两两成对"},
};
