import type {ShotSpec} from './shots';

export const SHOT_SPECS: Record<string, ShotSpec> = {
  SC01: {kind: 'title', lecname: "盘的读法", agenda: ["一格三层", "三层分工", "全盘逐宫念", "天干回头处", "只读一宫", "主证与附证", "顺时针方向"]},
  SC02: {kind: 'pan', pan: {plate: ['', '丑', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'read', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.004}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.008}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.012}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.016}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.02}, {k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.0}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.0}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.0}, {k: 'tz', zhi: "巳", gz: "寅", rel: 0.0}, {k: 'tz', zhi: "午", gz: "卯", rel: 0.0}, {k: 'tz', zhi: "未", gz: "辰", rel: 0.0}, {k: 'tz', zhi: "申", gz: "巳", rel: 0.0}, {k: 'tz', zhi: "酉", gz: "午", rel: 0.0}, {k: 'tz', zhi: "戌", gz: "未", rel: 0.0}, {k: 'tz', zhi: "亥", gz: "申", rel: 0.0}, {k: 'tz', zhi: "子", gz: "酉", rel: 0.0}, {k: 'tz', zhi: "丑", gz: "戌", rel: 0.0}, {k: 'tz', zhi: "寅", gz: "亥", rel: 0.0}, {k: 'tz', zhi: "卯", gz: "子", rel: 0.0}, {k: 'tz', zhi: "辰", gz: "丑", rel: 0.0}, {k: 'tg', zhi: "巳", gz: "戊", rel: 0.0}, {k: 'tg', zhi: "午", gz: "己", rel: 0.0}, {k: 'tg', zhi: "未", gz: "庚", rel: 0.0}, {k: 'tg', zhi: "申", gz: "辛", rel: 0.0}, {k: 'tg', zhi: "酉", gz: "壬", rel: 0.0}, {k: 'tg', zhi: "戌", gz: "癸", rel: 0.0}, {k: 'tg', zhi: "亥", gz: "甲", rel: 0.0}, {k: 'tg', zhi: "子", gz: "乙", rel: 0.0}, {k: 'tg', zhi: "丑", gz: "甲", rel: 0.0}, {k: 'tg', zhi: "寅", gz: "乙", rel: 0.0}, {k: 'tg', zhi: "卯", gz: "丙", rel: 0.0}, {k: 'tg', zhi: "辰", gz: "丁", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.35}], centerNote: "说出三层各是什么"}},
  SC03: {kind: 'slide', slide: {kind: 'points', title: "三层分工", sub: "说出各层管什么", items: ["年命支从司人宫铺开，就铺在这一层", "得病日的干从年命支宫起，铺在这一层", "三层各管各的，谁也不能顶谁的位", "地盘支，只管定位", "天盘干，管定药号的证位"]}},
  SC04: {kind: 'pan', pan: {plate: ['', '丑', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'read', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.004}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.008}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.012}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.016}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.02}, {k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.0}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.0}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.0}, {k: 'tz', zhi: "巳", gz: "寅", rel: 0.0}, {k: 'tz', zhi: "午", gz: "卯", rel: 0.0}, {k: 'tz', zhi: "未", gz: "辰", rel: 0.0}, {k: 'tz', zhi: "申", gz: "巳", rel: 0.0}, {k: 'tz', zhi: "酉", gz: "午", rel: 0.0}, {k: 'tz', zhi: "戌", gz: "未", rel: 0.0}, {k: 'tz', zhi: "亥", gz: "申", rel: 0.0}, {k: 'tz', zhi: "子", gz: "酉", rel: 0.0}, {k: 'tz', zhi: "丑", gz: "戌", rel: 0.0}, {k: 'tz', zhi: "寅", gz: "亥", rel: 0.0}, {k: 'tz', zhi: "卯", gz: "子", rel: 0.0}, {k: 'tz', zhi: "辰", gz: "丑", rel: 0.0}, {k: 'tg', zhi: "巳", gz: "戊", rel: 0.0}, {k: 'tg', zhi: "午", gz: "己", rel: 0.0}, {k: 'tg', zhi: "未", gz: "庚", rel: 0.0}, {k: 'tg', zhi: "申", gz: "辛", rel: 0.0}, {k: 'tg', zhi: "酉", gz: "壬", rel: 0.0}, {k: 'tg', zhi: "戌", gz: "癸", rel: 0.0}, {k: 'tg', zhi: "亥", gz: "甲", rel: 0.0}, {k: 'tg', zhi: "子", gz: "乙", rel: 0.0}, {k: 'tg', zhi: "丑", gz: "甲", rel: 0.0}, {k: 'tg', zhi: "寅", gz: "乙", rel: 0.0}, {k: 'tg', zhi: "卯", gz: "丙", rel: 0.0}, {k: 'tg', zhi: "辰", gz: "丁", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.35}], centerNote: "会念整盘"}},
  SC05: {kind: 'pan', pan: {plate: ['', '丑', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "不再以为漏字"}},
  SC06: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "知道读盘只看一宫"}},
  SC07: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "知道分层记录"}},
  SC08: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'gan', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.004}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.008}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.012}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.016}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.02}, {k: 'tz', zhi: "辰", gz: "亥", carry: true, rel: 0.0}, {k: 'tz', zhi: "巳", gz: "子", carry: true, rel: 0.0}, {k: 'tz', zhi: "午", gz: "丑", carry: true, rel: 0.0}, {k: 'tz', zhi: "未", gz: "寅", carry: true, rel: 0.0}, {k: 'tz', zhi: "申", gz: "卯", carry: true, rel: 0.0}, {k: 'tz', zhi: "酉", gz: "辰", carry: true, rel: 0.0}, {k: 'tz', zhi: "戌", gz: "巳", carry: true, rel: 0.0}, {k: 'tz', zhi: "亥", gz: "午", carry: true, rel: 0.0}, {k: 'tz', zhi: "子", gz: "未", carry: true, rel: 0.0}, {k: 'tz', zhi: "丑", gz: "申", carry: true, rel: 0.0}, {k: 'tz', zhi: "寅", gz: "酉", carry: true, rel: 0.0}, {k: 'tz', zhi: "卯", gz: "戌", carry: true, rel: 0.0}, {k: 'tg', zhi: "亥", gz: "甲", carry: true, rel: 0.0}, {k: 'tg', zhi: "子", gz: "乙", carry: true, rel: 0.0}, {k: 'tg', zhi: "丑", gz: "丙", carry: true, rel: 0.0}, {k: 'tg', zhi: "寅", gz: "丁", carry: true, rel: 0.0}, {k: 'tg', zhi: "卯", gz: "戊", carry: true, rel: 0.0}, {k: 'tg', zhi: "辰", gz: "己", carry: true, rel: 0.0}, {k: 'tg', zhi: "巳", gz: "庚", carry: true, rel: 0.0}, {k: 'tg', zhi: "午", gz: "辛", carry: true, rel: 0.0}, {k: 'tg', zhi: "未", gz: "壬", carry: true, rel: 0.0}, {k: 'tg', zhi: "申", gz: "癸", carry: true, rel: 0.0}, {k: 'tg', zhi: "酉", gz: "甲", carry: true, rel: 0.0}, {k: 'tg', zhi: "戌", gz: "乙", carry: true, rel: 0.0}], centerNote: "知道年命干不进来"}},
  SC09: {kind: 'slide', slide: {kind: 'points', title: "不可凭空补", sub: "记住不补", items: ["书里有些地方只给属相，不给年干", "可那副盘就成了自己画的，书上的原盘不长这样"]}},
  SC10: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.2474}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.4447}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.6421}, {k: 'focus', zhi: "寅", rel: 0.7221}], centerNote: "会自查这一项"}},
  SC11: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.2344}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.2525}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.4187}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.6031}, {k: 'focus', zhi: "寅", rel: 0.6831}], centerNote: "会自查这一项"}},
  SC12: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.0631}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.0762}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.0893}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.2241}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "会自查重漏"}},
  SC13: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "会自查跳字"}},
  SC14: {kind: 'slide', slide: {kind: 'points', title: "自查表", sub: "知道要写下来", items: ["顺着走，是乙丙丁戊己庚辛壬癸", "第一行写司地，是不是第三宫", "十个干铺完，剩下两宫回头从甲再起", "四项都过了，这副盘才能用", "有一项不合，就回头重排"]}},
  SC15: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.0805}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.1111}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.1416}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.1722}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "记住代价"}},
  SC16: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "不会排反"}},
  SC17: {kind: 'slide', slide: {kind: 'points', title: "下期预告", sub: "知道下期讲取号", items: ["反盘拿去对歌诀，也能对上几条，那才是最坑的", "讲到这儿，检查这一关算是过了", "下期内容，讲药号的规矩", "把这些讲透，你手上这副盘才算真能出号"]}},
};
