import type {ShotSpec} from './shots';

export const SHOT_SPECS: Record<string, ShotSpec> = {
  SC01: {kind: 'title', lecname: "地支归六经", agenda: ["六经落位", "对宫同经", "规律由来", "六经字号一览", "六经次序", "边界警示", "医案三段"]},
  SC02: {kind: 'slide', slide: {kind: 'points', title: "六经落位", sub: "会报任一支归哪经", items: ["配的时候不用死背，看那个规律就够了", "相隔六位的两支，六经是一样的", "子和午，都是少阴", "丑和未，都是太阴", "寅和申，都是少阳"]}},
  SC03: {kind: 'slide', slide: {kind: 'points', title: "对宫同经", sub: "说出规律", items: ["卯和酉，都是阳明", "辰和戌，都是太阳", "巳和亥，都是厥阴"]}},
  SC04: {kind: 'slide', slide: {kind: 'points', title: "规律由来", sub: "明白一气配两支", items: ["六气一周，是六步，十二支一周是十二步", "六气相配十二支，一气正好配上两支", "盘上看到辰，你不用查表，直接知道戌也是太阳", "有人会问，这六条经各管什么事呢"]}},
  SC05: {kind: 'zihaoTable', rows: [["太阳", "十三字号 · 三附证", "", ""], ["阳明", "五行字号 · 霍 劳", "", ""], ["少阳", "纪", "", ""], ["太阴", "母", "", ""], ["少阴", "天 人 地", "", ""], ["厥阴", "乾 坤", "", ""]], title: "六经字号一览", hotRow: 5},
  SC06: {kind: 'slide', slide: {kind: 'points', title: "六经次序", sub: "记住深浅次序", items: ["天字号，和人字号，是天干直取，地字号三个证位要归并", "厥阴，最里一层", "从外往里数，一条比一条深", "次序记熟了，查歌诀的时候心里就有个深浅"]}},
  SC07: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "记住这条边界"}},
  SC08: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'read', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.004}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.008}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.012}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.016}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.02}, {k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.0}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.0}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.0}, {k: 'tz', zhi: "巳", gz: "子", rel: 0.0}, {k: 'tz', zhi: "午", gz: "丑", rel: 0.0}, {k: 'tz', zhi: "未", gz: "寅", rel: 0.0}, {k: 'tz', zhi: "申", gz: "卯", rel: 0.0}, {k: 'tz', zhi: "酉", gz: "辰", rel: 0.0}, {k: 'tz', zhi: "戌", gz: "巳", rel: 0.0}, {k: 'tz', zhi: "亥", gz: "午", rel: 0.0}, {k: 'tz', zhi: "子", gz: "未", rel: 0.0}, {k: 'tz', zhi: "丑", gz: "申", rel: 0.0}, {k: 'tz', zhi: "寅", gz: "酉", rel: 0.0}, {k: 'tz', zhi: "卯", gz: "戌", rel: 0.0}, {k: 'tz', zhi: "辰", gz: "亥", rel: 0.0}, {k: 'tg', zhi: "巳", gz: "庚", rel: 0.0}, {k: 'tg', zhi: "午", gz: "辛", rel: 0.0}, {k: 'tg', zhi: "未", gz: "壬", rel: 0.0}, {k: 'tg', zhi: "申", gz: "癸", rel: 0.0}, {k: 'tg', zhi: "酉", gz: "甲", rel: 0.0}, {k: 'tg', zhi: "戌", gz: "乙", rel: 0.0}, {k: 'tg', zhi: "亥", gz: "甲", rel: 0.0}, {k: 'tg', zhi: "子", gz: "乙", rel: 0.0}, {k: 'tg', zhi: "丑", gz: "丙", rel: 0.0}, {k: 'tg', zhi: "寅", gz: "丁", rel: 0.0}, {k: 'tg', zhi: "卯", gz: "戊", rel: 0.0}, {k: 'tg', zhi: "辰", gz: "己", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.35}], centerNote: "会读单宫"}},
  SC09: {kind: 'pan', pan: {plate: ['', '亥', '甲', '卯'], sansi: ['卯', '午', '未'], stage: 'sansi', events: [{k: 'mark', zhi: "卯", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "卯", rel: 0.55}], centerNote: "知道上见换则经换"}},
  SC10: {kind: 'pan', pan: {plate: ['', '亥', '甲', '卯'], sansi: ['卯', '午', '未'], stage: 'sansi', events: [{k: 'mark', zhi: "卯", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "卯", rel: 0.55}], centerNote: "说出什么是上见"}},
  SC11: {kind: 'slide', slide: {kind: 'points', title: "上见两用处", sub: "知道上见管什么", items: ["拿混了，后面全错"]}},
  SC12: {kind: 'slide', slide: {kind: 'points', title: "干管号", sub: "记住别拿错", items: ["接下来，把手足经说细一点"]}},
  SC13: {kind: 'slide', slide: {kind: 'points', title: "手足经表", sub: "知道有这张表", items: ["十二行：支 / 手足经 / 脏腑"]}},
  SC14: {kind: 'slide', slide: {kind: 'points', title: "手足经规律", sub: "记住巳亥例外", items: ["巳是手厥阴，亥，是足厥阴，只有这一对跟别的不同", "再仔细看，前六支，是五条足经加一个手经，就是巳", "后六支，是五条手经加一个足经，就是亥", "盘上写成，子丑寅卯辰巳为脏，午未申酉戌亥为腑"]}},
  SC15: {kind: 'slide', slide: {kind: 'points', title: "医案三段", sub: "会分三段写", items: ["上见，是盘上的定位词", "说寅日上见酉，只，是在说盘面，不是在说病人身上有什么", "写医案的时候，三样东西要分开写"]}},
  SC16: {kind: 'slide', slide: {kind: 'points', title: "下期预告", sub: "知道下期是重头戏", items: ["上见，是司天那一格上的天盘地支，管定经，也管附证", "三段混在一起，就容易把术数模型当成病情描述", "地支，归六经，一支一条经，对宫两支同一条经", "取药号看同一格的天盘干，不看地支", "手足经那十二个经脉名，先不用背，知道有这张表就够了"]}},
};
