import type {ShotSpec} from './shots';

export const SHOT_SPECS: Record<string, ShotSpec> = {
  SC01: {kind: 'title', lecname: "药号总诀", agenda: ["药号拆字", "格子与流水", "两个干", "归并表七条", "两条外推", "直取字号", "下期钩子卡"]},
  SC02: {kind: 'slide', slide: {kind: 'points', title: "药号拆字", sub: "会说前字管什么、后字管什么", items: ["前一个字，是字号，定的是经病范围", "后一个字，是证位，定这一段里的第几条", "归并的意思，是把超出证数的天干按规矩退回范围里", "证数少的字号，天干要归并"]}},
  SC03: {kind: 'slide', slide: {kind: 'points', title: "格子与流水", sub: "明白归并是格子不够用", items: ["左四个空格（四证），右十枚天干牌"]}},
  SC04: {kind: 'slide', slide: {kind: 'points', title: "两个干", sub: "会分本干与药号干", items: ["一个，是天盘本干，盘上直接读出来的那个字", "一个，是药号干，归并之后落到号上的那个字", "格子只有四个，流水有十个，多出来的只能记回格子里", "归并之前，先分清两个干", "只有不需归并的字号，它们才是同一个字"]}},
  SC05: {kind: 'slide', slide: {kind: 'points', title: "归并表七条", sub: "能复述水与地的归并", items: ["喝字号，是底本自带的", "第一，月字号六证，庚辛归戊，壬癸归己", "第二，破字号六证，依月字号退法，也归戊己", "第三，水字号四证，戊己庚归丙，辛壬癸归丁"]}},
  SC06: {kind: 'slide', slide: {kind: 'points', title: "两条外推", sub: "记住这两条不是铁律", items: ["用的时候心里要有数，它，是个便查的法子，不是硬规矩", "九证的坤和坎最松，只有癸一个字超出来，退给壬就完了", "还剩两个字号，传本里没有明文", "湿字号六证，本书按六证通例处理，同破字号", "痉字号五证，按次序递退处理", "第三块，哪些字号不归并"]}},
  SC07: {kind: 'slide', slide: {kind: 'points', title: "直取字号", sub: "说出直取的判据", items: ["后半部例题里，申命甲寅日天盘干庚，书写作天庚"]}},
  SC08: {kind: 'slide', slide: {kind: 'points', title: "直取字号", sub: "说出直取的判据", items: ["戌命丁卯日天盘干壬，书写作天壬", "要是按六证字号去归并，前者要变成天乙", "后者按三证归并要变成天丙，都跟原书不合", "证数齐全的字号直取，证数不全的字号归并", "拿到一个字号，先数证数", "少阳，只有纪字号一组"]}},
  SC09: {kind: 'bingchuan', dir: '逆', cells: [{d: "第1日", gz: "乙未", jing: "太阴"}, {d: "第2日", gz: "甲午", jing: "少阴"}, {d: "第3日", gz: "癸巳", jing: "厥阴"}, {d: "第4日", gz: "壬辰", jing: "太阳"}, {d: "第5日", gz: "辛卯", jing: "阳明"}, {d: "第6日", gz: "庚寅", jing: "少阳"}]},
  SC10: {kind: 'slide', slide: {kind: 'points', title: "总诀六句", sub: "知道总诀管整条顺序", items: ["六句韵文整屏陈列，逐句标注管哪一步"]}},
  SC11: {kind: 'handTable', rows: [["亥", "甲寅", "寅", "巳", "辰", "酉", "丁", "阳明", "", ""], ["", "", "", "", "", "", "", "", "", ""]], hotRow: 0},
  SC12: {kind: 'pan', pan: {plate: null, sansi: ['寅', '巳', '辰'], stage: 'dipan', events: [{k: 'dz', zhi: "子", rel: 0.05}, {k: 'dz', zhi: "丑", rel: 0.0809}, {k: 'dz', zhi: "寅", rel: 0.1118}, {k: 'dz', zhi: "卯", rel: 0.1427}, {k: 'dz', zhi: "辰", rel: 0.1736}, {k: 'dz', zhi: "巳", rel: 0.2045}, {k: 'dz', zhi: "午", rel: 0.2355}, {k: 'dz', zhi: "未", rel: 0.2664}, {k: 'dz', zhi: "申", rel: 0.2973}, {k: 'dz', zhi: "酉", rel: 0.3282}, {k: 'dz', zhi: "戌", rel: 0.3591}, {k: 'dz', zhi: "亥", rel: 0.39}], centerNote: "能报出司天司地司人"}},
  SC13: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.0991}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.1482}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.1974}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.2465}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "知道两样从哪宫起"}},
  SC14: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'read', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.004}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.008}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.012}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.016}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.02}, {k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.0}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.0}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.0}, {k: 'tz', zhi: "巳", gz: "子", rel: 0.0}, {k: 'tz', zhi: "午", gz: "丑", rel: 0.0}, {k: 'tz', zhi: "未", gz: "寅", rel: 0.0}, {k: 'tz', zhi: "申", gz: "卯", rel: 0.0}, {k: 'tz', zhi: "酉", gz: "辰", rel: 0.0}, {k: 'tz', zhi: "戌", gz: "巳", rel: 0.0}, {k: 'tz', zhi: "亥", gz: "午", rel: 0.0}, {k: 'tz', zhi: "子", gz: "未", rel: 0.0}, {k: 'tz', zhi: "丑", gz: "申", rel: 0.0}, {k: 'tz', zhi: "寅", gz: "酉", rel: 0.0}, {k: 'tz', zhi: "卯", gz: "戌", rel: 0.0}, {k: 'tz', zhi: "辰", gz: "亥", rel: 0.0}, {k: 'tg', zhi: "巳", gz: "庚", rel: 0.0}, {k: 'tg', zhi: "午", gz: "辛", rel: 0.0}, {k: 'tg', zhi: "未", gz: "壬", rel: 0.0}, {k: 'tg', zhi: "申", gz: "癸", rel: 0.0}, {k: 'tg', zhi: "酉", gz: "甲", rel: 0.0}, {k: 'tg', zhi: "戌", gz: "乙", rel: 0.0}, {k: 'tg', zhi: "亥", gz: "甲", rel: 0.0}, {k: 'tg', zhi: "子", gz: "乙", rel: 0.0}, {k: 'tg', zhi: "丑", gz: "丙", rel: 0.0}, {k: 'tg', zhi: "寅", gz: "丁", rel: 0.0}, {k: 'tg', zhi: "卯", gz: "戊", rel: 0.0}, {k: 'tg', zhi: "辰", gz: "己", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.35}], centerNote: "跟得住整条链路"}},
  SC15: {kind: 'slide', slide: {kind: 'points', title: "落款格式", sub: "知道一步一验怎么写", items: ["写医案和写校记，都该，是这个格式"]}},
  SC16: {kind: 'zihaoTable', rows: [["太阳", "十三字号 · 三附证", "", ""], ["阳明", "五行字号 · 霍 劳", "", ""], ["少阳", "纪", "", ""], ["太阴", "母", "", ""], ["少阴", "天 人 地", "", ""], ["厥阴", "乾 坤", "", ""]], title: "六经字号一览", hotRow: 0},
};
