import type {ShotSpec} from './shots';

export const SHOT_SPECS: Record<string, ShotSpec> = {
  SC01: {kind: 'title', lecname: "读盘次第二十四例", agenda: ["工具已齐", "九步流程", "四类分开记", "次序不能乱", "例题十栏", "填表演示", "过关标准"]},
  SC02: {kind: 'slide', slide: {kind: 'points', title: "工具已齐", sub: "知道还差次序", items: ["先把读盘的次第立起来，再拿二十四则例题过一遍", "读到这一讲，你手上的家伙已经齐了", "起盘会了，读盘会了，取号会了，查方会了", "排一盘出来，从哪下手，先看哪一样，后看哪一样，这得有个固定次序"]}},
  SC03: {kind: 'slide', slide: {kind: 'points', title: "九步流程", sub: "说出九步", items: ["次序乱了，容易漏东西", "读一盘，按九步走", "第一条，记下输入", "第三条，铺天盘地支和天盘天干", "支从司人，干从年命", "第四条，读司天宫的上见支，定六经"]}},
  SC04: {kind: 'slide', slide: {kind: 'points', title: "四类分开记", sub: "记住要分类", items: ["原书明确的，是底子，据法推出的是推论，外部补入的是别人家的材料", "把它们分开，是给自己的记录留一条后路", "九步的次序也不，是随便排的", "前五步，是做盘，做完盘才有东西可读", "第六到第八步，是加菜，看这一盘要不要用别的法"]}},
  SC05: {kind: 'bingchuan', dir: '逆', cells: [{d: "第1日", gz: "丁酉", jing: "阳明"}, {d: "第2日", gz: "丙申", jing: "少阳"}, {d: "第3日", gz: "乙未", jing: "太阴"}, {d: "第4日", gz: "甲午", jing: "少阴"}, {d: "第5日", gz: "癸巳", jing: "厥阴"}, {d: "第6日", gz: "壬辰", jing: "太阳"}]},
  SC06: {kind: 'handTable', rows: [["亥", "甲寅", "寅", "巳", "辰", "酉", "丁", "阳明", "", ""], ["", "", "", "", "", "", "", "", "", ""]], hotRow: 0},
  SC07: {kind: 'handTable', rows: [["亥", "甲寅", "寅", "巳", "辰", "酉", "丁", "阳明", "", ""], ["", "", "", "", "", "", "", "", "", ""]], hotRow: 0},
  SC08: {kind: 'slide', slide: {kind: 'points', title: "补充指标与出处", sub: "知道为什么最要紧", items: ["哪一句，是原书原文，哪一句是推出来的，都要落在这一栏", "将来你要引用，就引这一栏里的出处", "没写出处的东西，过三个月你也不敢用"]}},
  SC09: {kind: 'slide', slide: {kind: 'points', title: "读盘口气三段", sub: "会分三段说", items: ["还有一件事容易被忽略，读盘的口气", "按后半部的起法，本例司天为寅，司地为巳，司人为辰", "到这一步，事实说完"]}},
  SC10: {kind: 'slide', slide: {kind: 'points', title: "范句逐句上屏", sub: "会照着说", items: ["收尾那一句，是今天的边界", "三句说完，一段合格的读盘就齐了"]}},
  SC11: {kind: 'slide', slide: {kind: 'points', title: "两句话不能说", sub: "记住红线", items: ["一句，是把算出来的结果说成必然发生的预言", "另一句，是把书中无方说成现实里无药可治", "前者，是替古人吹牛，后者是吓人", "后半部的例题，是全书最可靠的一份基准"]}},
  SC12: {kind: 'slide', slide: {kind: 'points', title: "二十四例全表", sub: "知道这是基准", items: ["因为它数目最多，还能逐格复算", "我们前面讲的以后半部为准，靠的就是这二十四则"]}},
  SC13: {kind: 'slide', slide: {kind: 'points', title: "二十四例全表", sub: "知道这是基准", items: ["因为它数目最多，还能逐格复算", "我们前面讲的以后半部为准，靠的就是这二十四则"]}},
  SC14: {kind: 'slide', slide: {kind: 'points', title: "逐例范读·一", sub: "会读一行", items: ["三司，是子卯寅", "药号震甲，方用大陷胸丸"]}},
  SC15: {kind: 'slide', slide: {kind: 'points', title: "逐例范读·一", sub: "会读一行", items: ["三司，是子卯寅", "药号震甲，方用大陷胸丸"]}},
  SC16: {kind: 'slide', slide: {kind: 'points', title: "逐例范读·三", sub: "会读一行", items: ["药号纪丙，方用小柴胡汤", "三司，是寅巳辰", "药号天庚，方用桃花汤"]}},
  SC17: {kind: 'slide', slide: {kind: 'points', title: "逐例范读·三", sub: "会读一行", items: ["药号纪丙，方用小柴胡汤", "三司，是寅巳辰", "药号天庚，方用桃花汤"]}},
  SC18: {kind: 'slide', slide: {kind: 'points', title: "逐例范读·四", sub: "会读一行", items: ["药号纪壬，方用小柴胡汤", "三司，是子卯寅", "药号破甲，方用桂枝加桂汤"]}},
  SC19: {kind: 'slide', slide: {kind: 'points', title: "逐例范读·四", sub: "会读一行", items: ["三司，是子卯寅", "药号乾乙，方用白虎汤"]}},
  SC20: {kind: 'slide', slide: {kind: 'points', title: "逐例范读·四", sub: "会读一行", items: ["三司，是子卯寅", "药号乾乙，方用白虎汤"]}},
  SC21: {kind: 'slide', slide: {kind: 'points', title: "逐例范读·四", sub: "会读一行", items: ["三司，是辰未午", "药号纪壬，方用小柴胡汤"]}},
  SC22: {kind: 'slide', slide: {kind: 'points', title: "逐例范读·四", sub: "会读一行", items: ["三司，是辰未午", "药号纪壬，方用小柴胡汤"]}},
  SC23: {kind: 'pan', pan: {plate: ['', '酉', '丁', '酉'], sansi: ['酉', '子', '丑'], stage: 'sansi', events: [{k: 'mark', zhi: "酉", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "酉", rel: 0.55}], centerNote: "知道怎么用"}},
  SC24: {kind: 'slide', slide: {kind: 'points', title: "第十二则", sub: "明白混写在哪", items: ["书文写的，是得到天干丁", "挑准一则，自己从头排一遍，把七栏填出来，再跟表对"]}},
  SC25: {kind: 'slide', slide: {kind: 'points', title: "第十五则", sub: "明白两层", items: ["水字号，里头辛壬癸归丁，所以药号是水丁", "第十五则，主经是阳明", "两层并着写，主号的霍丁在，附证的霍乱也在"]}},
  SC26: {kind: 'slide', slide: {kind: 'points', title: "过关标准", sub: "知道自己练什么", items: ["随便报一个年命和一个病日，你能把七栏顺出来", "二十四则走完，工具和用法就都齐了", "下期内容，我们上整盘"]}},
  SC27: {kind: 'pan', pan: {plate: ['', '酉', '丁', '酉'], sansi: ['酉', '子', '丑'], stage: 'sansi', events: [{k: 'mark', zhi: "酉", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "酉", rel: 0.55}], centerNote: "知道下期上整盘"}},
};
