import type {ShotSpec} from './shots';

export const SHOT_SPECS: Record<string, ShotSpec> = {
  SC01: {kind: 'title', lecname: "太阳字号", agenda: ["十三字号盘", "成立条件", "反例卡", "定位表·上半", "定位表·下半", "十三对十二", "下期钩子卡"]},
  SC02: {kind: 'zihaoTable', rows: [["太阳", "十三字号 · 三附证", "", ""], ["阳明", "五行字号 · 霍 劳", "", ""], ["少阳", "纪", "", ""], ["太阴", "母", "", ""], ["少阴", "天 人 地", "", ""], ["厥阴", "乾 坤", "", ""]], title: "六经字号一览", hotRow: 0},
  SC03: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'read', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.004}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.008}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.012}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.016}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.02}, {k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "卯", text: "1", tone: "ink", rel: 0.0}, {k: 'mark', zhi: "辰", text: "2", tone: "ink", rel: 0.0}, {k: 'mark', zhi: "巳", text: "3", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "巳", text: "司地", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "辰", text: "司人", tone: "cinnabar", rel: 0.0}, {k: 'tz', zhi: "巳", gz: "子", rel: 0.0}, {k: 'tz', zhi: "午", gz: "丑", rel: 0.0}, {k: 'tz', zhi: "未", gz: "寅", rel: 0.0}, {k: 'tz', zhi: "申", gz: "卯", rel: 0.0}, {k: 'tz', zhi: "酉", gz: "辰", rel: 0.0}, {k: 'tz', zhi: "戌", gz: "巳", rel: 0.0}, {k: 'tz', zhi: "亥", gz: "午", rel: 0.0}, {k: 'tz', zhi: "子", gz: "未", rel: 0.0}, {k: 'tz', zhi: "丑", gz: "申", rel: 0.0}, {k: 'tz', zhi: "寅", gz: "酉", rel: 0.0}, {k: 'tz', zhi: "卯", gz: "戌", rel: 0.0}, {k: 'tz', zhi: "辰", gz: "亥", rel: 0.0}, {k: 'tg', zhi: "巳", gz: "庚", rel: 0.0}, {k: 'tg', zhi: "午", gz: "辛", rel: 0.0}, {k: 'tg', zhi: "未", gz: "壬", rel: 0.0}, {k: 'tg', zhi: "申", gz: "癸", rel: 0.0}, {k: 'tg', zhi: "酉", gz: "甲", rel: 0.0}, {k: 'tg', zhi: "戌", gz: "乙", rel: 0.0}, {k: 'tg', zhi: "亥", gz: "甲", rel: 0.0}, {k: 'tg', zhi: "子", gz: "乙", rel: 0.0}, {k: 'tg', zhi: "丑", gz: "丙", rel: 0.0}, {k: 'tg', zhi: "寅", gz: "丁", rel: 0.0}, {k: 'tg', zhi: "卯", gz: "戊", rel: 0.0}, {k: 'tg', zhi: "辰", gz: "己", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.35}], centerNote: "说出太阳病的判据"}},
  SC04: {kind: 'pan', pan: {plate: ['', '亥', '甲', '寅'], sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "明白先认经再认号"}},
  SC05: {kind: 'table', cols: [{t: '地盘'}, {t: '司地'}, {t: '地盘'}, {t: '司地'}], rows: [["子", "卯", "午", "酉"], ["丑", "辰", "未", "戌"], ["寅", "巳", "申", "亥"], ["卯", "午", "酉", "子"], ["辰", "未", "戌", "丑"], ["巳", "申", "亥", "寅"]], rowH: 46, perCell: 5, x: 400, y: 232, w: 480, title: "顺数三宫对照", caption: "司天顺数三宫，本宫不算"},
  SC06: {kind: 'table', cols: [{t: '地盘'}, {t: '司地'}, {t: '地盘'}, {t: '司地'}], rows: [["子", "卯", "午", "酉"], ["丑", "辰", "未", "戌"], ["寅", "巳", "申", "亥"], ["卯", "午", "酉", "子"], ["辰", "未", "戌", "丑"], ["巳", "申", "亥", "寅"]], rowH: 46, perCell: 5, x: 400, y: 232, w: 480, title: "顺数三宫对照", caption: "司天顺数三宫，本宫不算"},
  SC07: {kind: 'table', cols: [{t: '地盘'}, {t: '司地'}, {t: '地盘'}, {t: '司地'}], rows: [["子", "卯", "午", "酉"], ["丑", "辰", "未", "戌"], ["寅", "巳", "申", "亥"], ["卯", "午", "酉", "子"], ["辰", "未", "戌", "丑"], ["巳", "申", "亥", "寅"]], rowH: 46, perCell: 5, x: 400, y: 232, w: 480, title: "顺数三宫对照", caption: "司天顺数三宫，本宫不算"},
  SC08: {kind: 'zihaoTable', rows: [["太阳", "十三字号 · 三附证", "", ""], ["阳明", "五行字号 · 霍 劳", "", ""], ["少阳", "纪", "", ""], ["太阴", "母", "", ""], ["少阴", "天 人 地", "", ""], ["厥阴", "乾 坤", "", ""]], title: "六经字号一览"},
  SC09: {kind: 'zihaoTable', rows: [["太阳", "十三字号 · 三附证", "", ""], ["阳明", "五行字号 · 霍 劳", "", ""], ["少阳", "纪", "", ""], ["太阴", "母", "", ""], ["少阴", "天 人 地", "", ""], ["厥阴", "乾 坤", "", ""]], title: "六经字号一览", hotRow: 0},
  SC10: {kind: 'table', cols: [{t: '地盘'}, {t: '司地'}, {t: '地盘'}, {t: '司地'}], rows: [["子", "卯", "午", "酉"], ["丑", "辰", "未", "戌"], ["寅", "巳", "申", "亥"], ["卯", "午", "酉", "子"], ["辰", "未", "戌", "丑"], ["巳", "申", "亥", "寅"]], rowH: 46, perCell: 5, x: 400, y: 232, w: 480, title: "顺数三宫对照", caption: "司天顺数三宫，本宫不算"},
  SC11: {kind: 'table', cols: [{t: '地盘'}, {t: '司地'}, {t: '地盘'}, {t: '司地'}], rows: [["子", "卯", "午", "酉"], ["丑", "辰", "未", "戌"], ["寅", "巳", "申", "亥"], ["卯", "午", "酉", "子"], ["辰", "未", "戌", "丑"], ["巳", "申", "亥", "寅"]], rowH: 46, perCell: 5, x: 400, y: 232, w: 480, title: "顺数三宫对照", caption: "司天顺数三宫，本宫不算"},
  SC12: {kind: 'slide', slide: {kind: 'points', title: "卯日两层", sub: "说出两层并行不二选一", items: ["两层并行，是这一层的要点", "主药号走坎字号，附证层标痉或者标湿", "排盘的时候两层都要写，不能只写一层", "主号填第七格，附证填底下那一排"]}},
  SC13: {kind: 'slide', slide: {kind: 'points', title: "读盘三句话", sub: "复述三句话", items: ["第一句，是防着你跳步，认了经就直接抄号", "第二句，是提醒你四样一起看，少一样号就不对", "第三句，是防着你只写一层，把附证当成主号的替代品"]}},
  SC14: {kind: 'slide', slide: {kind: 'points', title: "方剂提示", sub: "知道日字号方向", items: ["太阳字号的歌诀里，日字号多见桂枝一类的方"]}},
  SC15: {kind: 'slide', slide: {kind: 'points', title: "退字辨析", sub: "理解退是归并非倒盘", items: ["退的，是取号的次序，盘面照旧往前", "我认为取号，是两套轨道", "日支和上见定的，是开哪一扇门", "天盘干，定的，是门里第几格", "月字号六证，庚辛两个干退给戊，壬癸两个干退给己", "缺一样，就写不成原书那个号"]}},
  SC16: {kind: 'slide', slide: {kind: 'points', title: "笨办法卡", sub: "知道怎么练", items: ["把十二行抄在一张卡片上，只留日支和字号两列", "排完盘，先把卡片合上，自己答一遍", "答不上来再翻，翻上三次就记住了"]}},
  SC17: {kind: 'slide', slide: {kind: 'points', title: "下期钩子卡", sub: "知道下期讲五经与查方", items: ["讲到这里，本期内容就结束了", "下期内容，讲其余五经的字号，还有拿号查方的整套流程", "再加两个完整的取号例子，从司天一路推到方名", "下一讲逐经讲解，两个例子全程手推"]}},
};
