import type {ShotSpec} from './shots';

export const SHOT_SPECS: Record<string, ShotSpec> = {
  SC01: {kind: 'title', lecname: "校勘疑案", agenda: ["为什么要纠错", "两套起法", "含本宫·逐宫", "不含本宫·逐宫", "一宫之差", "第二例·甲子日", "五处异文"]},
  SC02: {kind: 'slide', slide: {kind: 'points', title: "为什么要纠错", sub: "知道校勘管什么", items: ["因为这本书不，是一次刻成的", "前后抄了几百年，刻过好几回，字句会走样"]}},
  SC03: {kind: 'slide', slide: {kind: 'points', title: "两套起法", sub: "知道有分歧", items: ["走样的地方不标出来，你按错的那句排盘，号就取错了", "先看第二十八章，两套起法的分歧", "一种在前半部，一种在后半部"]}},
  SC04: {kind: 'pan', pan: {plate: null, sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "会排前半部起法"}},
  SC05: {kind: 'pan', pan: {plate: null, sansi: ['寅', '巳', '辰'], stage: 'sansi', events: [{k: 'mark', zhi: "寅", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "寅", rel: 0.55}], centerNote: "会排后半部起法"}},
  SC06: {kind: 'table', cols: [{t: '地盘'}, {t: '司地'}, {t: '地盘'}, {t: '司地'}], rows: [["子", "卯", "午", "酉"], ["丑", "辰", "未", "戌"], ["寅", "巳", "申", "亥"], ["卯", "午", "酉", "子"], ["辰", "未", "戌", "丑"], ["巳", "申", "亥", "寅"]], rowH: 46, perCell: 5, x: 400, y: 232, w: 480, title: "顺数三宫对照", caption: "司天顺数三宫，本宫不算"},
  SC07: {kind: 'slide', slide: {kind: 'points', title: "第二例·甲子日", sub: "确认差法是固定的", items: ["寅宫，和卯宫，又，是一宫之差", "按后半部的算法，子宫先不算", "丑第一步，寅第二步，卯第三步，落到卯宫", "差这一宫，后面全变", "三司变了，天盘变了，六经变了，药号也变了"]}},
  SC08: {kind: 'slide', slide: {kind: 'points', title: "为什么会并存", sub: "知道不下断语", items: ["我的推断，是前半部成书早，后半部是后来补的", "也可能两套本来，就是不同来源的材料，被合到了一起", "书里定的，是以后半部为准", "补的人换了算法，改了例题，却没有回头改前面", "不管哪一种，我们都不去判谁对谁错", "只判一件事，哪一套跟例题和传本合得上"]}},
  SC09: {kind: 'slide', slide: {kind: 'points', title: "三条理由·一", sub: "记住第一条", items: ["第一，后半部例题多，能逐格复算"]}},
  SC10: {kind: 'slide', slide: {kind: 'points', title: "三条理由·二", sub: "记住第二条", items: ["按后半部的起法一条条算，三司对得上，上见对得上，药号，也对得上", "第二，后半部有附表可以交叉验证", "表和例能互相校正，一处错了另一处能显出来"]}},
  SC11: {kind: 'slide', slide: {kind: 'points', title: "三条理由·三", sub: "记住第三条", items: ["前半部例题少，也没有这样的附表", "第三，后半部的起法跟传本相合"]}},
  SC12: {kind: 'slide', slide: {kind: 'points', title: "冲突五步", sub: "会按次序处理矛盾", items: ["三条理由摆在一起，后半部的分量就压过前半部了"]}},
  SC13: {kind: 'slide', slide: {kind: 'points', title: "第一步·先看是不是起法不", sub: "会按次序处理矛盾", items: ["有些矛盾只，是起法不同造成的，不是错字", "把起法统一了，矛盾自己就没了"]}},
  SC14: {kind: 'slide', slide: {kind: 'points', title: "第二步·看同章的附表和后", sub: "会按次序处理矛盾", items: ["同一章里的表和例，往往能互相校正"]}},
  SC15: {kind: 'slide', slide: {kind: 'points', title: "第三步·看独立的传本", sub: "会按次序处理矛盾", items: ["传本之间相同的地方，可信度高"]}},
  SC16: {kind: 'slide', slide: {kind: 'points', title: "第四步·看能不能自校验", sub: "会按次序处理矛盾", items: ["比如一个字号只有五证，可达的天干却有六七个"]}},
  SC17: {kind: 'slide', slide: {kind: 'points', title: "第五步·仍不能定的，保留", sub: "会按次序处理矛盾", items: ["听到这儿你可能觉得奇怪，为什么不干脆定一个呢？", "因为硬定一个，等于把不确定藏起来"]}},
  SC18: {kind: 'slide', slide: {kind: 'points', title: "阙疑的含义", sub: "明白阙疑", items: ["藏起来的东西，将来会以更贵的方式冒出来", "阙疑这两个字，说的就是这件事", "拿不准的地方就摆着，把拿不准在哪儿标清楚"]}},
  SC19: {kind: 'slide', slide: {kind: 'points', title: "三种材料分层", sub: "会分层", items: ["研究底本里的页文，这，是最直接的材料", "读这本书会碰到三种材料，得分层放", "第一层，底本原文"]}},
  SC20: {kind: 'slide', slide: {kind: 'points', title: "传本清单", sub: "知道有哪些传本", items: ["读者分不清哪句，是古人的，哪句是后人推的", "传本之间有时相同，有时不同", "第三层，研究推导", "三层混在一起写，麻烦就来了"]}},
  SC21: {kind: 'slide', slide: {kind: 'points', title: "混写之害", sub: "知道为什么要分", items: ["书里列了五条校勘例，都，是常见错处", "后人推的东西，一旦被当成原书原文引出去，就再也收不回来"]}},
  SC22: {kind: 'slide', slide: {kind: 'points', title: "校勘例·第一条", sub: "会读校勘例", items: ["理由，是同卷例题和附表都作太阴", "理由，是从辰宫顺行到子，实得戊子", "理由，是天盘复算得辛，水字号，里辛壬癸归丁", "原文一律保留，不能径改", "第一条，十二属相受患证治例", "第二条，两感章说顺行到子位得丙子"]}},
  SC23: {kind: 'slide', slide: {kind: 'points', title: "校勘例·续四条", sub: "会读校勘例", items: ["理由，是丑未归太阴"]}},
  SC24: {kind: 'slide', slide: {kind: 'points', title: "五条路数", sub: "明白方法", items: ["理由，是太阳支是辰戌，这里缺一个戌字", "第五条，同章说辰成为太阳经", "五条看下来，路数是一样的", "都是拿机器算出来的结果，反过来校文本"]}},
  SC25: {kind: 'slide', slide: {kind: 'points', title: "异文并存", sub: "明白并存的意思", items: ["选定哪一说，就把理由和置信度公开"]}},
  SC26: {kind: 'slide', slide: {kind: 'points', title: "异文并存", sub: "明白并存的意思", items: ["选定哪一说，就把理由和置信度公开"]}},
  SC27: {kind: 'slide', slide: {kind: 'points', title: "下期预告", sub: "知道下期讲十则", items: ["十则一期讲完，看看研究，是怎么走的", "病传，太阴母字号的取号", "以后若能见到原刻本的影像，还能再核", "下期内容，进第三十章，已决疑案十则"]}},
};
