import type {ShotSpec} from './shots';

export const SHOT_SPECS: Record<string, ShotSpec> = {
  SC01: {kind: 'title', lecname: "已决疑案十则", agenda: ["十则为什么值钱", "三段框格式", "第一则·疑点", "第一则·查证", "第一则·定数循环", "第一则·两道手续", "十则的共同路子"]},
  SC02: {kind: 'slide', slide: {kind: 'points', title: "十则为什么值钱", sub: "知道本讲重点是查法", items: ["十则都，是已经解决了的疑难", "因为看结论最省事，也最没用", "结论会被新版本推翻，查证的路子不会"]}},
  SC03: {kind: 'bingchuan', dir: '逆', cells: [{d: "第1日", gz: "甲子", jing: "少阴"}, {d: "第2日", gz: "癸亥", jing: "厥阴"}, {d: "第3日", gz: "壬戌", jing: "太阳"}, {d: "第4日", gz: "辛酉", jing: "阳明"}, {d: "第5日", gz: "庚申", jing: "少阳"}, {d: "第6日", gz: "己未", jing: "太阴"}]},
  SC04: {kind: 'slide', slide: {kind: 'points', title: "第一则·疑点", sub: "知道疑在哪", items: ["桂枝汤挂在母甲条下，不在母乙条下"]}},
  SC05: {kind: 'bingchuan', dir: '逆', cells: [{d: "第1日", gz: "甲子", jing: "少阴"}, {d: "第2日", gz: "癸亥", jing: "厥阴"}, {d: "第3日", gz: "壬戌", jing: "太阳"}, {d: "第4日", gz: "辛酉", jing: "阳明"}, {d: "第5日", gz: "庚申", jing: "少阳"}, {d: "第6日", gz: "己未", jing: "太阴"}]},
  SC06: {kind: 'slide', slide: {kind: 'points', title: "第一则·定数循环", sub: "会自己算", items: ["先检查坎字号九证的证数，还有卯日可达的天干"]}},
  SC07: {kind: 'slide', slide: {kind: 'points', title: "第一则·两道手续", sub: "记住不可互相顶替", items: ["一算发现，它们用的都是旧起法"]}},
  SC08: {kind: 'slide', slide: {kind: 'points', title: "第二则·疑点", sub: "知道不是选一个", items: ["也就，是前一讲说的含本宫算法", "结论，是两层并读"]}},
  SC09: {kind: 'slide', slide: {kind: 'points', title: "第二则·旧起法", sub: "知道错在哪", items: ["两层同写，不是二选一"]}},
  SC10: {kind: 'pan', pan: {plate: ['', '申', '甲', '卯'], sansi: ['卯', '午', '未'], stage: 'read', events: [{k: 'mark', zhi: "卯", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "辰", text: "1", tone: "ink", rel: 0.004}, {k: 'mark', zhi: "巳", text: "2", tone: "ink", rel: 0.008}, {k: 'mark', zhi: "午", text: "3", tone: "cinnabar", rel: 0.012}, {k: 'mark', zhi: "午", text: "司地", tone: "cinnabar", rel: 0.016}, {k: 'mark', zhi: "未", text: "司人", tone: "cinnabar", rel: 0.02}, {k: 'mark', zhi: "卯", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "辰", text: "1", tone: "ink", rel: 0.0}, {k: 'mark', zhi: "巳", text: "2", tone: "ink", rel: 0.0}, {k: 'mark', zhi: "午", text: "3", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "午", text: "司地", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "未", text: "司人", tone: "cinnabar", rel: 0.0}, {k: 'tz', zhi: "巳", gz: "午", rel: 0.0}, {k: 'tz', zhi: "午", gz: "未", rel: 0.0}, {k: 'tz', zhi: "未", gz: "申", rel: 0.0}, {k: 'tz', zhi: "申", gz: "酉", rel: 0.0}, {k: 'tz', zhi: "酉", gz: "戌", rel: 0.0}, {k: 'tz', zhi: "戌", gz: "亥", rel: 0.0}, {k: 'tz', zhi: "亥", gz: "子", rel: 0.0}, {k: 'tz', zhi: "子", gz: "丑", rel: 0.0}, {k: 'tz', zhi: "丑", gz: "寅", rel: 0.0}, {k: 'tz', zhi: "寅", gz: "卯", rel: 0.0}, {k: 'tz', zhi: "卯", gz: "辰", rel: 0.0}, {k: 'tz', zhi: "辰", gz: "巳", rel: 0.0}, {k: 'tg', zhi: "巳", gz: "癸", rel: 0.0}, {k: 'tg', zhi: "午", gz: "甲", rel: 0.0}, {k: 'tg', zhi: "未", gz: "乙", rel: 0.0}, {k: 'tg', zhi: "申", gz: "甲", rel: 0.0}, {k: 'tg', zhi: "酉", gz: "乙", rel: 0.0}, {k: 'tg', zhi: "戌", gz: "丙", rel: 0.0}, {k: 'tg', zhi: "亥", gz: "丁", rel: 0.0}, {k: 'tg', zhi: "子", gz: "戊", rel: 0.0}, {k: 'tg', zhi: "丑", gz: "己", rel: 0.0}, {k: 'tg', zhi: "寅", gz: "庚", rel: 0.0}, {k: 'tg', zhi: "卯", gz: "辛", rel: 0.0}, {k: 'tg', zhi: "辰", gz: "壬", rel: 0.0}, {k: 'focus', zhi: "卯", rel: 0.35}], centerNote: "会自己复算"}},
  SC11: {kind: 'slide', slide: {kind: 'points', title: "第二则·两层并读", sub: "记住两层同写", items: ["传本明写，破字号下六证，亦依上太阳月字号下所退"]}},
  SC12: {kind: 'slide', slide: {kind: 'points', title: "第三则·传本作证", sub: "会推破字号", items: ["又有自注说，庚第七，所以用破字号下第七号药", "两处一对，破字号沿用月字号退法，就立住了", "湿字号按同一体例外推，置信度低一些"]}},
  SC13: {kind: 'slide', slide: {kind: 'points', title: "第三则·置信度分档", sub: "知道要标置信度", items: ["第四则，天字号为什么不归并"]}},
  SC14: {kind: 'slide', slide: {kind: 'points', title: "第四则·拿例验证", sub: "知道直取的依据", items: ["查证，是拿后半部的例题来验", "把庚归乙，把壬归丙"]}},
  SC15: {kind: 'slide', slide: {kind: 'points', title: "第四则·拿例验证", sub: "知道直取的依据", items: ["要是归并，前者该作天乙，后者该作天丙"]}},
  SC16: {kind: 'slide', slide: {kind: 'points', title: "第四则·结论", sub: "记住规则", items: ["证数齐全的字号，不能拿别的字号的归并规矩去套"]}},
  SC17: {kind: 'slide', slide: {kind: 'points', title: "第五则·缺四类", sub: "知道缺什么", items: ["问题，是底本只给了庚金受午火克一例", "缺的四类，是原书故意不说，还是根本没想到要写呢？", "第五则，五运受病的补泻怎样补足五类关系"]}},
  SC18: {kind: 'slide', slide: {kind: 'points', title: "第五则·归纳规矩", sub: "会推补泻", items: ["结论，是默认用归纳出来的规矩", "把运气学的那一套读法，一并保存下来"]}},
  SC19: {kind: 'slide', slide: {kind: 'points', title: "第五则·两说并列", sub: "知道不删", items: ["第六则，客主加临的表头与六之气异文"]}},
  SC20: {kind: 'table', cols: [{t: '地盘'}, {t: '司地'}, {t: '地盘'}, {t: '司地'}], rows: [["子", "卯", "午", "酉"], ["丑", "辰", "未", "戌"], ["寅", "巳", "申", "亥"], ["卯", "午", "酉", "子"], ["辰", "未", "戌", "丑"], ["巳", "申", "亥", "寅"]], rowH: 46, perCell: 5, x: 400, y: 232, w: 480, title: "顺数三宫对照", caption: "司天顺数三宫，本宫不算"},
  SC21: {kind: 'slide', slide: {kind: 'points', title: "第六则·机械复算", sub: "知道复算是依据", items: ["三十六格一算，结构就定了"]}},
  SC22: {kind: 'slide', slide: {kind: 'points', title: "第六则·结论", sub: "会分流", items: ["结论，是表头按数据结构解释", "另一个底本的写法，保留在异文记录里", "第七则，两感的子不宜戌有没有出处"]}},
  SC23: {kind: 'slide', slide: {kind: 'points', title: "第七则·明文判据", sub: "知道是明文", items: ["问题，是底本的两感例里出现了子与戌，出处一度不清"]}},
  SC24: {kind: 'slide', slide: {kind: 'points', title: "第七则·相刑另标", sub: "记住规则", items: ["结论，是两感歌的配对属于明文判据", "问题，是丁部只给方名和主治，没有逐味组成", "有明文，还需要后人去归纳吗？", "相刑另作标记，不参与判定", "第八则，十六方的药味从哪里来"]}},
  SC25: {kind: 'slide', slide: {kind: 'points', title: "第八则·据宋代方书补入", sub: "记住要挂出处", items: ["查证，是检索那部宋代方书，还有另外几家独立的转录", "结论，是十六方全部补齐", "但正文必须写明，是据那部方书补入", "第九则，欲解时的钟点，是不是古书原有", "问题，是书上列的是寅卯辰一类地支三辰，不写钟点", "三辰说的，是什么时段呢？"]}},
  SC26: {kind: 'sanQiuWuMu'},
  SC27: {kind: 'slide', slide: {kind: 'points', title: "第十则·不作必死", sub: "记住口气", items: ["结论，是只作凶险的提示，不分级，不作必死的断语", "要把这些理出条贯，方可断曰全凶", "三丘五墓跟棺墓法，不自己加权合并", "十则走完了，回头看那条共同的路子"]}},
  SC28: {kind: 'slide', slide: {kind: 'points', title: "十则的共同路子", sub: "会自己走一遍", items: ["再交代一句，这里算的都，是古籍算法的结果", "先找疑点，再查底本和传本，再复算，最后下结论并标出置信度", "结论会被新版本推翻，次序不会"]}},
  SC29: {kind: 'slide', slide: {kind: 'points', title: "下期预告", sub: "知道下期收尾", items: ["讲到这里，本期内容就结束了", "下期内容，讲还没定下来的那一批问题"]}},
};
