import type {ShotSpec} from './shots';

export const SHOT_SPECS: Record<string, ShotSpec> = {
  SC01: {kind: 'title', lecname: "两感欲解时", agenda: ["两感定义", "第一步·主盘", "第二步·孟仲季另起一宫", "起局宫表", "表里三组", "两感症歌列屏", "下期钩子卡"]},
  SC02: {kind: 'slide', slide: {kind: 'points', title: "两感定义", sub: "说出两感是什么", items: ["三阳算表，三阴算里", "表和里同时受病，就叫两感"]}},
  SC03: {kind: 'slide', slide: {kind: 'points', title: "第一步·主盘", sub: "知道第一步是旧活", items: ["两感的排法分两步，跟主盘不太一样"]}},
  SC04: {kind: 'slide', slide: {kind: 'points', title: "第一步·先按主盘那套七步", sub: "知道第一步是旧活", items: ["第一步，先按主盘那套七步走，得到一层落宫地支"]}},
  SC05: {kind: 'pan', pan: {plate: ['', '子', '庚', '辰'], sansi: ['辰', '未', '午'], stage: 'sansi', events: [{k: 'mark', zhi: "辰", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "辰", rel: 0.55}], centerNote: "知道多了一步"}},
  SC06: {kind: 'pan', pan: {plate: ['', '子', '庚', '辰'], sansi: ['辰', '未', '午'], stage: 'sansi', events: [{k: 'mark', zhi: "辰", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "辰", rel: 0.55}], centerNote: "知道多了一步"}},
  SC07: {kind: 'table', cols: [{t: '地盘'}, {t: '司地'}, {t: '地盘'}, {t: '司地'}], rows: [["子", "卯", "午", "酉"], ["丑", "辰", "未", "戌"], ["寅", "巳", "申", "亥"], ["卯", "午", "酉", "子"], ["辰", "未", "戌", "丑"], ["巳", "申", "亥", "寅"]], rowH: 46, perCell: 5, x: 400, y: 232, w: 480, title: "顺数三宫对照", caption: "司天顺数三宫，本宫不算"},
  SC08: {kind: 'slide', slide: {kind: 'points', title: "表里三组", sub: "会背三组", items: ["六经两两成对，就这三组", "两支所化的经落在同一组里，两感才成立"]}},
  SC09: {kind: 'slide', slide: {kind: 'points', title: "两感症歌列屏", sub: "知道有这首歌", items: ["歌里，是六组配对，这一首逐句念，念一句解释一句"]}},
  SC10: {kind: 'slide', slide: {kind: 'points', title: "配对盖十二支", sub: "知道是明文判据", items: ["六组数一数，子丑寅卯辰申，正好六对", "十二支一个不落，全配完了", "后半部有两个两感的例子，都命中了这首歌", "落宫得戌，合经得子"]}},
  SC11: {kind: 'slide', slide: {kind: 'points', title: "配对盖十二支", sub: "知道是明文判据", items: ["落宫得巳，合经得寅", "两个例子一对，这首歌就能当尺子用", "把第一个例子完整走一遍，你就有手感了"]}},
  SC12: {kind: 'pan', pan: {plate: ['', '子', '庚', '辰'], sansi: ['辰', '未', '午'], stage: 'sansi', events: [{k: 'mark', zhi: "辰", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "辰", rel: 0.55}], centerNote: "会自己推落宫"}},
  SC13: {kind: 'pan', pan: {plate: ['', '子', '庚', '辰'], sansi: ['辰', '未', '午'], stage: 'sansi', events: [{k: 'mark', zhi: "辰", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "巳", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "午", text: "2", tone: "ink", rel: 0.1896}, {k: 'mark', zhi: "未", text: "3", tone: "cinnabar", rel: 0.3291}, {k: 'mark', zhi: "未", text: "司地", tone: "cinnabar", rel: 0.4687}, {k: 'mark', zhi: "午", text: "司人", tone: "cinnabar", rel: 0.7286}, {k: 'focus', zhi: "辰", rel: 0.8086}], centerNote: "会自己推落宫"}},
  SC14: {kind: 'slide', slide: {kind: 'points', title: "戊子庚辰例·第二步·两感成立", sub: "会做判定", items: ["本经卡（太阳·落宫戌）/ 合经卡（少阴·合经子）"]}},
  SC15: {kind: 'slide', slide: {kind: 'points', title: "第二步·按孟仲季起局", sub: "会做判定", items: ["日支辰属四季，从辰宫起", "两支到齐，太阳配少阴", "翻表里那三组，太阳与少阴正是表里", "回头看歌里那一句子不宜戌，正好应上"]}},
  SC16: {kind: 'slide', slide: {kind: 'points', title: "相刑只标寅巳", sub: "记住相刑另标", items: ["相刑可以另作标记，但它不参与两感的判定"]}},
  SC17: {kind: 'slide', slide: {kind: 'points', title: "两种刑别混", sub: "不会混用", items: ["运气里说的金木相刑，那，是五行相刑", "跟地支三刑，是两回事，两个系统各说各的"]}},
  SC18: {kind: 'slide', slide: {kind: 'points', title: "治法边界", sub: "记住不进主取号", items: ["也就，是说，书上到成立为止，治法这一层是空的", "引用的时候要注明用的，是哪个版本，不能混着引", "要学治法，得另参两本书", "六经各有三辰当旺，叫欲解时"]}},
  SC19: {kind: 'slide', slide: {kind: 'points', title: "欲解时·六经三辰", sub: "会背六条", items: ["少阳的寅卯辰，寅，是厥阴的第三辰，卯是厥阴的第二辰", "三条经的三辰里，有两辰是共用的", "太阴的亥子丑，子被少阴借走，丑被少阴和厥阴两头占着", "按这类推法，六条经其实共用了一张十二支的网"]}},
  SC20: {kind: 'slide', slide: {kind: 'points', title: "钟点是今人换算", sub: "会区分原文与换算", items: ["换算的规矩，是子时从二十三点起，一辰两小时", "成无己说，是阳气得以复", "尤在泾说，是阳气充而邪乃解", "歌里只列地支三辰，一个钟点也没写"]}},
  SC21: {kind: 'slide', slide: {kind: 'points', title: "四种释义", sub: "知道解释不一", items: ["意思，是经气当旺的时候，病可能减轻，也可能加重"]}},
  SC22: {kind: 'slide', slide: {kind: 'points', title: "窗口不是承诺", sub: "记住口气", items: ["书上只给了地支三辰，它能支持的只有一句话，这一段可以观察"]}},
  SC23: {kind: 'slide', slide: {kind: 'points', title: "孟仲季日数", sub: "会读日数", items: ["三辰，是连着的三个地支", "本书按得病日的支来定日数，不往细里再推"]}},
  SC24: {kind: 'slide', slide: {kind: 'points', title: "三辰重叠", sub: "知道有重叠", items: ["重叠处怎么分，原书没有明说", "有说按各经的第一辰分的，也有说按起时归经的", "我不给它定死，排盘的时候把这一点记下来", "记下来，将来见着别的传本还能对"]}},
  SC25: {kind: 'slide', slide: {kind: 'points', title: "下期钩子卡", sub: "知道下期讲病传", items: ["六天怎么一天一天传过去，一天换一个字，这里面有一张很规整的表"]}},
};
