import type {ShotSpec} from './shots';

export const SHOT_SPECS: Record<string, ShotSpec> = {
  SC01: {kind: 'title', lecname: "五运客主", agenda: ["运与气的分界", "起例歌列屏", "五运旺支表", "五步流程", "不套主线", "土运旺支要分家", "分歧那一格"]},
  SC02: {kind: 'slide', slide: {kind: 'points', title: "运与气的分界", sub: "说出输入不同", items: ["五运受病看的，是运，客主加临看的是气", "两块看着像，输入其实不一样"]}},
  SC03: {kind: 'slide', slide: {kind: 'points', title: "起例歌列屏", sub: "知道有歌可查", items: ["歌是给记性好的人用的，表，是给干活的人用的", "歌里那点信息，一张表就装下了"]}},
  SC04: {kind: 'slide', slide: {kind: 'points', title: "五运旺支表", sub: "会查表", items: ["五运皆同旺处推，旺支，就是这张表的钥匙", "十个天干配五个运，一张表全查得到"]}},
  SC05: {kind: 'slide', slide: {kind: 'points', title: "五步流程", sub: "说出五步", items: ["就两样，得病日的干，和年命的支"]}},
  SC06: {kind: 'slide', slide: {kind: 'points', title: "第一步·由得病日的天干定", sub: "说出五步", items: ["第一步，由得病日的天干定五运"]}},
  SC07: {kind: 'slide', slide: {kind: 'points', title: "第二步·取这一运的旺支作", sub: "说出五步", items: ["第二步，取这一运的旺支作为人位"]}},
  SC08: {kind: 'slide', slide: {kind: 'points', title: "第三步·从旺支宫起放年命", sub: "说出五步", items: ["第三步，从旺支宫起放年命的地支，顺行到得病日的地支"]}},
  SC09: {kind: 'slide', slide: {kind: 'points', title: "第四步·读所得的支，定受", sub: "说出五步", items: ["顺行到受病支上，把干取出来"]}},
  SC10: {kind: 'slide', slide: {kind: 'points', title: "第五步·拿受病干支的五行", sub: "说出五步", items: ["第五步，拿受病干支的五行生克，作补泻的参考"]}},
  SC11: {kind: 'pan', pan: {plate: ['', '巳', '丙', '子'], sansi: ['子', '卯', '寅'], stage: 'sansi', events: [{k: 'mark', zhi: "子", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'mark', zhi: "丑", text: "1", tone: "ink", rel: 0.05}, {k: 'mark', zhi: "寅", text: "2", tone: "ink", rel: 0.2004}, {k: 'mark', zhi: "卯", text: "3", tone: "cinnabar", rel: 0.3509}, {k: 'mark', zhi: "卯", text: "司地", tone: "cinnabar", rel: 0.5013}, {k: 'mark', zhi: "寅", text: "司人", tone: "cinnabar", rel: 0.551}, {k: 'focus', zhi: "子", rel: 0.631}], centerNote: "不会拿司地去套"}},
  SC12: {kind: 'slide', slide: {kind: 'points', title: "土运旺支要分家", sub: "记住两处不同", items: ["上期土运在子，这张土运在未，跟上期那张是两处", "巳命，丙子日得病"]}},
  SC13: {kind: 'pan', pan: {plate: ['', '巳', '丙', '子'], sansi: ['子', '卯', '寅'], stage: 'sansi', events: [{k: 'mark', zhi: "子", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "子", rel: 0.55}], centerNote: "会自己推"}},
  SC14: {kind: 'slide', slide: {kind: 'points', title: "例题一·结果行", sub: "会读结果行", items: ["可两道例题实际用的都，是年命的支", "原书这里的括注，把本命写成了得病日的地支"]}},
  SC15: {kind: 'slide', slide: {kind: 'points', title: "五虎遁取干", sub: "知道这一干怎么来", items: ["本书从例题，同时把这处括注的矛盾记下来"]}},
  SC16: {kind: 'slide', slide: {kind: 'points', title: "括注矛盾", sub: "知道为什么从例题", items: ["我认为从例题，是对的，两例是同一个用法，括注多半是抄串了", "第一套，是本书默认的定旺者一法，分三小步", "相克，就取克的那个为旺", "相生，就取受生的那个为旺", "比和，两个同气俱旺"]}},
  SC17: {kind: 'slide', slide: {kind: 'points', title: "补泻三小步", sub: "说出三小步", items: ["火克金，克者，是火，旺者就是火", "泻用火的本味苦，补用火所胜的金的本味辛", "得出来四个字，泻苦补辛"]}},
  SC18: {kind: 'slide', slide: {kind: 'points', title: "庚金受午火克", sub: "会推补泻", items: ["(五行环) 上火→金，标"]}},
  SC19: {kind: 'slide', slide: {kind: 'points', title: "两套读法并列", sub: "知道为什么不删", items: ["第二套，是运气学的读法", "照这一说，泻的那一侧会得出泻咸补辛", "本书把两说并列，默认用第一说，另一说保留着", "两套并排摆着，谁也不删"]}},
  SC20: {kind: 'slide', slide: {kind: 'points', title: "自注的代号", sub: "明白自注一层", items: ["自注这一层，是看懂底本的钥匙"]}},
  SC21: {kind: 'pan', pan: {plate: ['', '丑', '甲', '子'], sansi: ['子', '卯', '寅'], stage: 'sansi', events: [{k: 'mark', zhi: "子", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "子", rel: 0.55}], centerNote: "会独立推第二例"}},
  SC22: {kind: 'slide', slide: {kind: 'points', title: "主气六步", sub: "会背六步", items: ["三之气，就是司天，六之气就是在泉", "初之气厥阴风木，二之气少阴君火，三之气少阳相火", "四之气太阴湿土，五之气阳明燥金，六之气太阳寒水", "客气六步，随司天移位", "同一套客气，落在不同的司天上，位置整个挪一遍"]}},
  SC23: {kind: 'pan', pan: {plate: ['', '丑', '甲', '子'], sansi: ['子', '卯', '寅'], stage: 'sansi', events: [{k: 'mark', zhi: "子", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "子", rel: 0.55}], centerNote: "知道客气年年变"}},
  SC24: {kind: 'slide', slide: {kind: 'points', title: "司天即在泉", sub: "记住两个位置", items: ["六步条上第 3、第 6 格同时描朱"]}},
  SC25: {kind: 'slide', slide: {kind: 'points', title: "司天即在泉", sub: "记住两个位置", items: ["六步条上第 3、第 6 格同时描朱"]}},
  SC26: {kind: 'slide', slide: {kind: 'points', title: "第四步·年命支从司人宫顺", sub: "知道有式子可用", items: ["第四步，年命支从司人宫顺行到司天宫，读所临之支定受病之经"]}},
  SC27: {kind: 'slide', slide: {kind: 'points', title: "第四步·是它独有的", sub: "知道有式子可用", items: ["前三步你早就会了，第四步才是新东西"]}},
  SC28: {kind: 'slide', slide: {kind: 'points', title: "客主加临四步", sub: "知道新在哪一步", items: ["进三宫，就是往前数三格"]}},
  SC29: {kind: 'pan', pan: {plate: ['', '子', '甲', '子'], sansi: ['子', '卯', '寅'], stage: 'sansi', events: [{k: 'mark', zhi: "子", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "子", rel: 0.55}], centerNote: "会自己推出戌"}},
  SC30: {kind: 'pan', pan: {plate: ['', '子', '甲', '子'], sansi: ['子', '卯', '寅'], stage: 'sansi', events: [{k: 'mark', zhi: "子", text: "司天", tone: "cinnabar", rel: 0.0}, {k: 'focus', zhi: "子", rel: 0.55}], centerNote: "会自己推出戌"}},
  SC31: {kind: 'slide', slide: {kind: 'points', title: "六乘六表", sub: "会查表", items: ["查法，是先找行，再找列，那一格就是答案", "行是主气六步，列是六纪", "分歧最大的一格，在六之气的子午之纪"]}},
  SC32: {kind: 'slide', slide: {kind: 'points', title: "分歧那一格", sub: "知道取舍依据", items: ["一个底本作太阳寒水，另一个作阳明燥金"]}},
  SC33: {kind: 'slide', slide: {kind: 'points', title: "下期预告", sub: "知道下期讲方", items: ["子午之纪的司天，是少阴君火，在泉该是阳明燥金", "本书采阳明燥金，给了三条理由", "第一，六之气就是在泉", "第二，另一个底本在初之气已经写了太阳寒水", "六之气再写一次，就重复了", "第三，按客气的机械推法去推，跟采阳明燥金的那张表，三十六格全合"]}},
};
