import type {ShotSpec} from './shots';

export const SHOT_SPECS: Record<string, ShotSpec> = {
  SC01: {kind: 'title', lecname: "未决与歌诀速查", agenda: ["为什么要摆未决", "三档未决", "第一档·四项", "三丘五墓基准", "太阴母字号", "五运补泻置信度", "最快的学法"]},
  SC02: {kind: 'slide', slide: {kind: 'points', title: "为什么要摆未决", sub: "明白为什么要讲未决", items: ["因为一门术数真正怕的，是争议被藏起来，有争议反倒正常"]}},
  SC03: {kind: 'slide', slide: {kind: 'points', title: "三档未决", sub: "知道有几档", items: ["依据，是底本里的两个例子", "藏着的地方，用的时候会咬人", "第一档，已经有默认口径，但还可以再复核", "第一项，三丘五墓的季节基准", "外部的占病材料多用节气，两说不一样"]}},
  SC04: {kind: 'slide', slide: {kind: 'points', title: "第一档·四项", sub: "知道哪些能用待核", items: ["第二项，太阴母字号在主线上怎么归并"]}},
  SC05: {kind: 'sanQiuWuMu'},
  SC06: {kind: 'slide', slide: {kind: 'points', title: "太阴母字号", sub: "知道缺什么", items: ["哪一系才，是原刻的，得等原刻本影像", "主线缺的那段明文，到现在还没找到", "可病传的循环归证，代替不了主线缺的那一段", "本书默认第一系，另两系并存", "第四项，五运受病的补泻规矩"]}},
  SC07: {kind: 'slide', slide: {kind: 'points', title: "太阴母字号", sub: "知道缺什么", items: ["哪一系才，是原刻的，得等原刻本影像", "主线缺的那段明文，到现在还没找到", "可病传的循环归证，代替不了主线缺的那一段", "本书默认第一系，另两系并存", "第四项，五运受病的补泻规矩"]}},
  SC08: {kind: 'slide', slide: {kind: 'points', title: "第二档·八项", sub: "知道开放项有哪些", items: ["纪字号，是不是十个天干都归纪甲，本书按直取办，还缺明确的归并原文", "三丘五墓和棺墓法怎么合看，底本没给合并的规矩，本书分两条并列", "怎么取舍，怎么合用，丁部说可以结合，前提是两套各自分明", "底本引的一则医案，全书找不到正文，只剩线索", "太阴母字号主线的归并注文，跟前面第二项是同一处", "外推的部分不能当定论用，碰到先记个待核"]}},
  SC09: {kind: 'slide', slide: {kind: 'points', title: "外推两处", sub: "知道是外推", items: ["两条都，是低置信度，标出来给你看", "一处，是病传第七日以后", "底本只写到六日，往后继续按同一个方向走，那是延伸，标续推"]}},
  SC10: {kind: 'slide', slide: {kind: 'points', title: "第三档·两处", sub: "知道要分开标", items: ["另一处，是两感成立以后的方剂映射"]}},
  SC11: {kind: 'slide', slide: {kind: 'points', title: "共同做法", sub: "明白阙疑的用法", items: ["八项里有两项，是同一处，就是太阴母字号主线缺的那段注文", "三档说完，你会发现一个共同的做法", "把这几条摆出来，摆出来的原因很简单，它们确实定不下来"]}},
  SC12: {kind: 'slide', slide: {kind: 'points', title: "速查一·六经", sub: "备查六经", items: ["六句话，六组地支，读盘的时候拿来对六经最快", "第二张，五运速查"]}},
  SC13: {kind: 'slide', slide: {kind: 'points', title: "速查二·五运", sub: "备查五运", items: ["土运的旺支，五运受病法用未"]}},
  SC14: {kind: 'slide', slide: {kind: 'points', title: "土运两法分家", sub: "记住不能混", items: ["同一张表上写着未，换到棺墓法就得换成子"]}},
  SC15: {kind: 'slide', slide: {kind: 'points', title: "速查三·五虎遁", sub: "备查五虎遁", items: ["两法混用，第一步就错", "甲己丙寅首，乙庚戊寅头，丙辛庚寅起", "丁壬壬寅顺，戊癸甲寅求"]}},
  SC16: {kind: 'slide', slide: {kind: 'points', title: "速查三·五虎遁", sub: "备查五虎遁", items: ["两法混用，第一步就错", "甲己丙寅首，乙庚戊寅头，丙辛庚寅起", "丁壬壬寅顺，戊癸甲寅求"]}},
  SC17: {kind: 'slide', slide: {kind: 'points', title: "速查四·校验例", sub: "知道怎么自测", items: ["七行自测卡（输入 / 关键结果）"]}},
  SC18: {kind: 'slide', slide: {kind: 'points', title: "速查四·校验例", sub: "知道怎么自测", items: ["七行自测卡（输入 / 关键结果）"]}},
  SC19: {kind: 'slide', slide: {kind: 'points', title: "自测范读二", sub: "会自测", items: ["七道里有一道，是戌命丁卯日，出来是天壬，猪肤汤"]}},
  SC20: {kind: 'slide', slide: {kind: 'points', title: "自测范读二", sub: "会自测", items: ["七道里有一道，是戌命丁卯日，出来是天壬，猪肤汤"]}},
  SC21: {kind: 'slide', slide: {kind: 'points', title: "七则通关", sub: "知道通关标准", items: ["《伤寒钤法》马宗素传本，两感那首歌出在这里"]}},
  SC22: {kind: 'slide', slide: {kind: 'points', title: "参考版本", sub: "知道去哪查原书", items: ["《重编伤寒必用运气全书》，熊宗立编", "《普济方》，字号归并的几条明文出这里", "《卜筮全书》明姚际隆，三丘五墓的歌诀出这里"]}},
  SC23: {kind: 'slide', slide: {kind: 'points', title: "转录警告", sub: "知道要回看", items: ["关键的字句，还得回看图版或者点校本", "第六到第九讲读盘取号查方，那是把主线走通", "霍乱劳复，痉湿喝，两感，欲解时，病传，三丘五墓，五运，运气方"]}},
  SC24: {kind: 'slide', slide: {kind: 'points', title: "全课回望", sub: "知道课走完了", items: ["二十一讲听下来，你会感觉到一件事"]}},
  SC25: {kind: 'slide', slide: {kind: 'points', title: "收尾", sub: "收尾完整", items: ["哪一套起法为准，哪一个字号能用，哪一句该存疑，全是取舍"]}},
  SC26: {kind: 'slide', slide: {kind: 'points', title: "结语·先算再说", sub: "记住第一句", items: ["算得快的人多，敢标出不确定的人少", "课讲完了，留三句话", "任何一条结论，能从纸上重来一遍的才算数", "重不出来的，先放下，查出处，再下判断", "第二句，分清是谁说的"]}},
  SC27: {kind: 'slide', slide: {kind: 'points', title: "结语·分清是谁说的", sub: "记住第二句", items: ["原书的话，传本的话，后人的推导，今人的换算"]}},
  SC28: {kind: 'slide', slide: {kind: 'points', title: "结语·存疑不丢", sub: "记住第三句", items: ["第三句，存疑不丢"]}},
  SC29: {kind: 'slide', slide: {kind: 'points', title: "最快的学法", sub: "知道怎么练", items: ["还是这套做法，掐，指一算，把算法拆开给你看", "拿一支笔，把后半部那二十四个例题算一遍", "算过之后，再回头读那些争议，判断自己就有了", "二十一讲，从三司一路走到阙疑，一条线走完"]}},
};
